dist: bionic

# Travis is set to build whenever a branch is pushed,
# but we only want that behavior for master
# all PRs still run tests on every push
branches:
  only:
    - master

git:
  depth: false  # shallow git clone

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

install:
  - "[ $CXX = g++ ] && export CXX=g++-9 || true"  # force GCC run to use GCC 9

script:
  - cmake . && cmake --build . --target test_app
  - ./test_app
