dist: bionic

# Travis is set to build whenever a branch is pushed,
# but we only want that behavior for master
# all PRs still run tests on every push
branches:
  only:
    - master

git:
  depth: false  # shallow git clone

language: cpp

compiler:
  - gcc
  - clang

env:
  - CXX_STANDARD=11
  - CXX_STANDARD=14
  - CXX_STANDARD=17

install:
  - pip install cmake>=3.14

script:
  - cmake -S . -B build -DCMAKE_CXX_STANDARD=$CXX_STANDARD .
  - cmake --build build --target test_hdltypes
  - ./build/tests/test_hdltypes
