dist: bionic

# Travis is set to build whenever a branch is pushed,
# but we only want that behavior for master
# all PRs still run tests on every push
branches:
  only:
    - master

git:
  depth: false  # shallow git clone

language: cpp

compiler:
  - gcc
  - clang

env:
  - CXX_STANDARD=14
  - CXX_STANDARD=17

script:
  - cmake -DCMAKE_CXX_STANDARD=$CXX_STANDARD .
  - cmake --build . --target test_app
  - ./test_app
