name: Functional Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: [11, 14, 17]
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install CMake
      run: |
        python -m pip install --upgrade pip
        pip install "cmake>=3.14"
    - name: Install Compilers
      run: |
        sudo apt update
        sudo apt install clang g++
    - name: Run Tests
      run: |
        cmake -S . -B build/ -DCMAKE_CXX_FLAGS="-Wall -Wextra" -DCMAKE_CXX_STANDARD=${{matrix.standard}}
        cmake --build build/ --target test_hdltypes
        ./build/tests/test_hdltypes
      env:
        CXX: ${{matrix.compiler}}

  manylinux2014:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: |
        export PATH=/opt/python/cp38-cp38/bin:$PATH
        python -m pip install --upgrade pip
        pip install "cmake>=3.14"
    - name: Run Tests
      run: |
        export PATH=/opt/python/cp38-cp38/bin:$PATH
        cmake -S . -B build/ -DCMAKE_CXX_FLAGS="-Wall -Wextra" -DCMAKE_CXX_STANDARD=11
        cmake --build build/ --target test_hdltypes
        ./build/tests/test_hdltypes

