name: Functional Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: [14, 17]
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install CMake
      run: |
        python -m pip install --upgrade pip
        pip install "cmake>=3.14"
    - name: Install Compilers
      run: |
        sudo apt update
        sudo apt install clang g++
    - name: Run Tests
      run: |
        cmake -S . -B build/ -DCMAKE_CXX_FLAGS="-Wall -Wextra -O0 -g --coverage" -DCMAKE_CXX_STANDARD=${{matrix.standard}}
        cmake --build build/ --target test_hdltypes
        ./build/tests/test_hdltypes
      env:
        CXX: ${{matrix.compiler}}
    - name: Upload Coverage
      if: matrix.compiler == 'g++'
      run: |
        bash <(curl -s https://codecov.io/bash)
